### ISSUE TITLE
Extend folder structure

### ISSUE THREAD

**Issue by jcolomb** [rostools/prodigenr#124]
linked to #119,

A possiblity is to use the structure describe in : Colomb, Julien, Thorsten Arendt, Keisuke Sehara, and The Gin-Tonic team. “Towards a Standardized Research Folder Structure.” Generation Research, 2021. https://doi.org/10.25815/WCY6-M233.

**Comment by lwjohnst86** [comment]
O neat! Thanks! My current updates are focused on more maintenance work, so won't be adding more folder styles any time soon.

What's the advantage of having so many folders with those long and descriptive names rather than having lots of files with similar descriptive names? If using files rather than folders, transitions to e.g. a distill/bookdown website would be minimal work.

**Comment by jcolomb** [comment]
It is a question of human readability. Research in data organisation show that the use of folders help people remember how they organised stuff, also finding files in a long list is difficult.
These kind of project folders are usually not turning into websites (but a website could be a nice template to add ?).

I have lots to do ATM, but I may come back with a PR in the future...

**Comment by jcolomb** [comment]
we moved our work to github, see template at https://github.com/tonic-team/Tonic-Research-Project-Template
and documentation https://gin-tonic.netlify.app/

Both work in progress ;)

**Comment by lwjohnst86** [comment]
I'm minimizing maintenance and scope for this package, so closing this.
